[workspace]
members = [
  "ballast-sysctrl-pac",
  "ballast-mpc-pac",
  "ballast-hpc-pac",
]

[workspace.dependencies]
bare-metal = "1.0"
vcell = "0.1"
critical-section = "1.1"
riscv = "0.11"
riscv-rt = "0.12"
